### ISSUE TITLE
About GT_SignalsToCut_VIPL.xlsx

### ISSUE THREAD

**Issue by ChainShoeTall** [deividbotina-alv/rtrppg#4]
May I konw how the content in GT_SignalsToCut_VIPL.xlsx was extracted? Seem not provided in the VIPL-HR dataset and I didn't find the references for cutting the signals

**Comment by deividbotina-alv** [comment]
Dear ChainShoeTall,

Thank you for your query regarding the GT_SignalsToCut_VIPL.xlsx file and its relevance to the VIPL-HR dataset. The information you're looking for can be found in the research paper titled "RTrPPG: An Ultra Light 3DCNN for Real-Time Remote Photoplethysmography," specifically in Section 5 under "Implementation details", in the subsection titled "Ground truth adaptation".

In this section, the paper explains that during the database acquisition, some anomalies were observed in the ground truth signals. These inconsistencies, such as gaps and false peaks, were typically found at the beginning and end of the acquisitions. They were primarily due to the movement of the subjects or failures in the acquisition devices. To address this, we performed a ground truth selection step. This involved individually checking the ground truth signals to select only the continuous segments with reliable ground truth morphology.

For the sake of reproducibility and clarity, we have provided a supplementary file that contains detailed information about these cropped signals. This file is the GT_SignalsToCut_VIPL.xlsx you mentioned. It serves as a reference for cutting the signals to ensure that the network training is done using only reliable ground truth data.

I hope this answers your question. Feel free to reach out if you need any more information!

Best regards,

Deivid.

**Comment by ChainShoeTall** [comment]
> Dear ChainShoeTall,
> 
> Thank you for your query regarding the GT_SignalsToCut_VIPL.xlsx file and its relevance to the VIPL-HR dataset. The information you're looking for can be found in the research paper titled "RTrPPG: An Ultra Light 3DCNN for Real-Time Remote Photoplethysmography," specifically in Section 5 under "Implementation details", in the subsection titled "Ground truth adaptation".
> 
> In this section, the paper explains that during the database acquisition, some anomalies were observed in the ground truth signals. These inconsistencies, such as gaps and false peaks, were typically found at the beginning and end of the acquisitions. They were primarily due to the movement of the subjects or failures in the acquisition devices. To address this, we performed a ground truth selection step. This involved individually checking the ground truth signals to select only the continuous segments with reliable ground truth morphology.
> 
> For the sake of reproducibility and clarity, we have provided a supplementary file that contains detailed information about these cropped signals. This file is the GT_SignalsToCut_VIPL.xlsx you mentioned. It serves as a reference for cutting the signals to ensure that the network training is done using only reliable ground truth data.
> 
> I hope this answers your question. Feel free to reach out if you need any more information!
> 
> Best regards,
> 
> Deivid.

Thank you, I appreciate your kind and detailed response! Best wishes to you as well!
